### ISSUE TITLE
API throughs this exception.

### ISSUE THREAD

**Issue by shahbaz213** [farimarwat/WifiMaster#1]
Certificate pinning failure!
                                                                                                      Peer certificate chain:
                                                                                                        sha256/lFQK/E6BG12P0jJx8dO4O0t3sgPZfQprjn8Ks/ypkjI=: CN=api.instabridge.com
                                                                                                        sha256/jQJTbIh0grw0/1TkHSumWb+Fs0Ggogr621gT3PvPKG0=: CN=R3,O=Let's Encrypt,C=US
                                                                                                        sha256/C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=: CN=ISRG Root X1,O=Internet Security Research Group,C=US
                                                                                                      Pinned certificates for api.instabridge.com:
                                                                                                        sha256/KxZ0miFi0NzxuZJM0fcaHaLWArIoAXDrfYIY5uAcqfU=

**Comment by farimarwat** [comment]
Solved and closed
