### ISSUE TITLE
Issue 

### ISSUE THREAD

**Issue by Hamad854** [farimarwat/WifiMaster#2]
TAG                     com.example.wifimanager              E  Certificate pinning failure!
                                                                                                      Peer certificate chain:
                                                                                                        sha256/6AFOffG6wYBUUcpkIk5YdcHVk/rVpT/lKlF0nVPmp5o=: CN=api.instabridge.com
                                                                                                        sha256/jQJTbIh0grw0/1TkHSumWb+Fs0Ggogr621gT3PvPKG0=: CN=R3,O=Let's Encrypt,C=US
                                                                                                        sha256/C5+lpZ7tcVwmwQIMcRtPbsQtWLABXhQzejna0wHFr8M=: CN=ISRG Root X1,O=Internet Security Research Group,C=US
                                                                                                      Pinned certificates for api.instabridge.com:
                                                                                                        sha256/KxZ0miFi0NzxuZJM0fcaHaLWArIoAXDrfYIY5uAcqfU=

**Comment by farimarwat** [comment]
working on

**Comment by farimarwat** [comment]
Solved and closing

**Comment by Hamad854** [comment]
JazaKallah
